# workspace.yml
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
 name: dev2-env
 namespace: tf-operator-git
spec:
 organization: tfcloud-sb
 secretsMountPath: "/tmp/secrets"
 module:
   source: "git::https://github.com/sbabbar/tf-operator-git"
 variables:
   - key: instance_type
     value: t2.micro
     sensitive: false
     environmentVariable: false
   - key: instance_count
     value: "2"
     sensitive: false
     environmentVariable: false
   - key: instance_name
     value: my-ec-dev
     sensitive: false
     environmentVariable: false
   - key: ami
     value: "ami-0915bcb5fa77e4892"
     sensitive: false
     environmentVariable: false
   - key: AWS_ACCESS_KEY_ID
     sensitive: true
     environmentVariable: true
   - key: AWS_SECRET_ACCESS_KEY
     sensitive: true
     environmentVariable: true
